tags:
  - name: User Signup
  - name: User Login
  - name: User Post

components:
  schemas:
    user:
      type: object
      properties:
        name:
          type: string
          example: prashant123
        email:
          type: string
          example: prashant.sharma@appinventiv.com
        password:
          type: string
        mobile_no:
          type: number
        age:
          type: number
      required:
        - name
        - email
        - password
        - age
        - mobile_no

paths:
  /routes/sign_route:
    post:
      summary: Create a new user in the database
      tags:
        - User Signup
      description: Register user with their details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: Created success
        '406':
          description: Value not accepted
        '500':
          description: Internal server error

  /login/login:
    post:
      summary: Create a user in the database
      tags:
        - User Login
      description: Give permission to the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: number
      responses:
        '201':
          description: Login successful
        '406':
          description: Value not found
        '500':
          description: Internal server error

  /routes/post_routes:
    post:
      summary: Insert a new post
      tags:
        - User Post
      description: Insert a post into the user's account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: object
                count:
                  type: number
                content:
                  type: string
      responses:
        '201':
          description: Post created successfully
        '406':
          description: Value not found
        '500':
          description: Internal server error
